export {default as mindmartians} from './mindmartians.jpg'
export {default as bgmi} from './bgmi.jpg'
export {default as chennai600032} from './chennai600032.jpg'
export {default as clashofmeme} from './clashofmeme.png'
export {default as freefire} from './freefire.jpg'
export {default as justintime} from './justintime.jpg'
export {default as paperpresentation} from './paperpresentation.png'
export {default as photography} from './photography.jpg'
export {default as plasticore} from './plasticore.png'
export {default as posterpresentation} from './posterpresentation.png'
export {default as surpriseevent} from './surpriseevent.png'
export {default as trialbytrivia} from './trialbytrivia.png'
export {default as wackyart} from './wackyart.png'
export {default as workshop} from './workshop.png'

